spring:
  application:
    name: graphql-java-tools-demo
  servlet:
    multipart:
      enabled: true
      location: /tmp

# in-memory h2 datasource configuration
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:apidb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;INIT=CREATE SCHEMA IF NOT EXISTS apidb
    driver-class-name: org.h2.Driver
    username: sa
    hikari:
      idle-timeout: 10000
      pool-name: h2-hikari-cp
      minimum-idle: 2
      maximum-pool-size: 5

spring.jpa.hibernate.naming.physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.properties.hibernate.show_sql: true
spring.jpa.properties.hibernate.format_sql: true
spring.jpa.properties.hibernate.dialect: org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.use-new-id-generator-mappings: true
spring.jpa.hibernate.ddl-auto: create-drop
spring.h2.console.enabled: true
spring.h2.console.settings.web-allow-others: true
