spring:
  application:
    name: graphql-subscription-demo

graphql:
  servlet:
    subscriptions:
      websocket:
        path: /subscriptions
    tracingEnabled: true

graphql.servlet.exception-handlers-enabled: true

management.endpoints.web.exposure.include: health, info, metrics
